language: node_js
sudo: false
cache:
  directories:
  - node_modules
  - bower_components
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: 1/h2akyvFFMwmaZtZ0gq8-Iz9u7gcaf8edfFuLeW-3NKo/XkZ1SUBowqO1qgx0WBZHYiGks1z8rBnnpW3E2NpNAvf2yhiALTNTTvgZ/v8Nv4qX0K58mus8LxjV+2pKyAu3+/B0gdvUl8Cxj8alIuEPAZm8I=
    project: mypwa-8fc19
    local-dir: dist
    acl: public_read
    on:
      branch: develop
      tags: true
  - provider: firebase
    skip_cleanup: true
    token:
      secure: 1/h2akyvFFMwmaZtZ0gq8-Iz9u7gcaf8edfFuLeW-3NKo/XkZ1SUBowqO1qgx0WBZHYiGks1z8rBnnpW3E2NpNAvf2yhiALTNTTvgZ/v8Nv4qX0K58mus8LxjV+2pKyAu3+/B0gdvUl8Cxj8alIuEPAZm8I=
    project: mypwa-8fc19
    local-dir: dist
    acl: public_read
    on:
      branch: master
